### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Fensterbank** [FABtotum/fabui-colibri#200]
Hello,

I followed the wiki to format SD Card and sucessfully went through the first installation web interface until the system wanted to restart (with this 60 seconds timer).
But: Never any light went red, blue or whatever. It blinks yellow like ever. I also doesn't beep. It makes nothing with the Fabtotum.

After the timer passed, nothing happened.
I connected my monitor and realized, lighttpd wasn't even started, so I rebooted the system.
When I watch Colibri starting on monitor all looks fine, lighttpd ist starting, FabtotumServices.py is running, ethernet is working...
but the system is dead. When I open the IP address in browser, it is loading (so lighttpd listens to the port) but nothing happens.

When I reboot, I see
`[FAIL] Stopping FABUI WebSocket Server`

During boot Starting the WebSocket Server succeeded, so I think this thing crashed.

I have the first Fabtotum from the crowdfunding. Is Colibri even compatible with my Fabtotum model?

I attach a few log messages. Other log files are empty or not relevant.

**/var/log/syslog**
```
...
Sep  9 15:34:24 fabtotum user.err kernel: [   35.816292] SQUASHFS error: lzo decompression failed, data probably corrupt
Sep  9 15:34:24 fabtotum user.err kernel: [   35.816346] SQUASHFS error: squashfs_read_data failed to read block 0x25d6cb
Sep  9 15:34:24 fabtotum user.err kernel: [   35.822091] SQUASHFS error: lzo decompression failed, data probably corrupt
Sep  9 15:34:24 fabtotum user.err kernel: [   35.822136] SQUASHFS error: squashfs_read_data failed to read block 0x25d6cb
Sep  9 15:34:24 fabtotum user.err kernel: [   35.824555] SQUASHFS error: lzo decompression failed, data probably corrupt
Sep  9 15:34:24 fabtotum user.err kernel: [   35.824602] SQUASHFS error: squashfs_read_data failed to read block 0x25d6cb
Sep  9 15:34:24 fabtotum user.err kernel: [   35.830335] SQUASHFS error: lzo decompression failed, data probably corrupt
Sep  9 15:34:24 fabtotum user.err kernel: [   35.830376] SQUASHFS error: squashfs_read_data failed to read block 0x25d6cb
Sep  9 15:34:24 fabtotum user.err kernel: [   35.838527] SQUASHFS error: lzo decompression failed, data probably corrupt
Sep  9 15:34:24 fabtotum user.err kernel: [   35.838581] SQUASHFS error: squashfs_read_data failed to read block 0x25d6cb
Sep  9 15:34:24 fabtotum user.err kernel: [   35.843400] SQUASHFS error: lzo decompression failed, data probably corrupt
Sep  9 15:34:24 fabtotum user.err kernel: [   35.843451] SQUASHFS error: squashfs_read_data failed to read block 0x25d6cb
Sep  9 15:35:06 fabtotum daemon.info connmand[1162]: wlan0 {newlink} index 3 address 00:0F:13:99:14:66 mtu 1500
Sep  9 15:35:06 fabtotum daemon.info connmand[1162]: wlan0 {newlink} index 3 operstate 2 <DOWN>
Sep  9 15:35:06 fabtotum daemon.info connmand[1162]: wlan0 {newlink} index 3 address 00:0F:13:99:14:66 mtu 1500
Sep  9 15:35:06 fabtotum daemon.info connmand[1162]: wlan0 {newlink} index 3 operstate 2 <DOWN>
Sep  9 15:35:06 fabtotum daemon.info avahi-daemon[1283]: Found user 'avahi' (UID 70) and group 'avahi' (GID 70).
Sep  9 15:35:06 fabtotum daemon.info avahi-daemon[1283]: Successfully dropped root privileges.
Sep  9 15:35:06 fabtotum daemon.info avahi-daemon[1283]: avahi-daemon 0.6.31 starting up.
Sep  9 15:35:06 fabtotum daemon.warn avahi-daemon[1283]: WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Sep  9 15:35:06 fabtotum daemon.info avahi-daemon[1283]: Loading service file /etc/avahi/services/fabtotum.service.
Sep  9 15:35:06 fabtotum daemon.info avahi-daemon[1283]: Loading service file /etc/avahi/services/sftp-ssh.service.
Sep  9 15:35:06 fabtotum daemon.info avahi-daemon[1283]: Loading service file /etc/avahi/services/ssh.service.
Sep  9 15:35:08 fabtotum daemon.info avahi-daemon[1283]: Joining mDNS multicast group on interface eth0.IPv4 with address 10.13.37.200.
Sep  9 15:35:08 fabtotum daemon.info avahi-daemon[1283]: New relevant interface eth0.IPv4 for mDNS.
Sep  9 15:35:08 fabtotum daemon.info avahi-daemon[1283]: Network interface enumeration completed.
Sep  9 15:35:08 fabtotum daemon.info avahi-daemon[1283]: Registering new address record for 10.13.37.200 on eth0.IPv4.
Sep  9 15:35:08 fabtotum daemon.info avahi-daemon[1283]: Registering HINFO record with values 'ARMV6L'/'LINUX'.
Sep  9 15:35:08 fabtotum daemon.info : starting pid 1286, tty '/dev/tty1': '/sbin/getty -L  tty1 0 vt100 '
Sep  9 15:35:08 fabtotum daemon.info avahi-daemon[1283]: Server startup complete. Host name is fabtotum.local. Local service cookie is 63032776.
Sep  9 15:35:09 fabtotum daemon.info avahi-daemon[1283]: Service "fabtotum" (/etc/avahi/services/ssh.service) successfully established.
Sep  9 15:35:09 fabtotum daemon.info avahi-daemon[1283]: Service "fabtotum" (/etc/avahi/services/sftp-ssh.service) successfully established.
Sep  9 15:35:09 fabtotum daemon.info avahi-daemon[1283]: Service "Fabtotum Personal Fabricator 3D Printer (fabtotum)" (/etc/avahi/services/fabtotum.service) successfully established.
Sep  9 15:35:15 fabtotum user.info kernel: [   46.291053] uart-pl011 20201000.uart: no DMA platform data
Sep  9 15:35:41 fabtotum user.err kernel: [   73.093278] SQUASHFS error: lzo decompression failed, data probably corrupt
Sep  9 15:35:41 fabtotum user.err kernel: [   73.093328] SQUASHFS error: squashfs_read_data failed to read block 0x25d6cb
Sep  9 15:37:15 fabtotum user.err kernel: [  166.281947] SQUASHFS error: lzo decompression failed, data probably corrupt
Sep  9 15:37:15 fabtotum user.err kernel: [  166.281990] SQUASHFS error: squashfs_read_data failed to read block 0x2c07c6
```

**/var/log/fabui/FabtotumServices.log**
```
[2017-09-09 15:35:15,091]: sender thread: started
[2017-09-09 15:35:15,097]: receiver thread: started
[2017-09-09 15:35:15,102]:  serial has no cancel_read
[2017-09-09 15:35:15,106]: All threads started
Traceback (most recent call last):
  File "/usr/share/fabui/ext/py//FabtotumServices.py", line 171, in <module>
    ws.connect();
  File "/usr/lib/python2.7/site-packages/ws4py/client/__init__.py", line 209, in connect
    self.sock.connect(self.bind_addr)
  File "/mnt/development/colibri-buildroot/output/packages/python/usr/lib/python2.7/socket.py", line 228, in meth
socket.error: [Errno 111] Connection refused
```

**/var/log/fabui/setCamera.log**
```
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x7ceb70 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
writing empty config
Camera enabled: True
Camera version: v1
```

**/var/log/lighttpd**
```
2017-06-13 13:52:57: (log.c.164) server started 
2017-06-13 13:52:57: (mod_fastcgi.c.1112) the fastcgi-backend /usr/bin/php-cgi failed to start: 
2017-06-13 13:52:57: (mod_fastcgi.c.1116) child exited with status 5 /usr/bin/php-cgi 
2017-06-13 13:52:57: (mod_fastcgi.c.1119) If you're trying to run your app as a FastCGI backend, make sure you're using the FastCGI-enabled version.
If this is PHP on Gentoo, add 'fastcgi' to the USE flags. 
2017-06-13 13:52:57: (mod_fastcgi.c.1406) [ERROR]: spawning fcgi failed. 
2017-06-13 13:52:57: (server.c.1022) Configuration of plugins failed. Going down. 
2017-09-09 13:20:47: (log.c.164) server started 
2017-09-09 13:21:39: (mod_fastcgi.c.1754) connect failed: Connection refused on unix:/run/php-fcgi.socket-0 
2017-09-09 13:21:39: (mod_fastcgi.c.3021) backend died; we'll disable it for 1 seconds and send the request to another backend instead: reconnects: 0 load: 1 
2017-09-09 13:21:39: (mod_fastcgi.c.1112) the fastcgi-backend /usr/bin/php-cgi failed to start: 
2017-09-09 13:21:39: (mod_fastcgi.c.1116) child exited with status 5 /usr/bin/php-cgi 
2017-09-09 13:21:39: (mod_fastcgi.c.1119) If you're trying to run your app as a FastCGI backend, make sure you're using the FastCGI-enabled version.
If this is PHP on Gentoo, add 'fastcgi' to the USE flags. 
2017-09-09 13:21:39: (mod_fastcgi.c.2838) ERROR: spawning fcgi failed. 
2017-09-09 13:34:16: (server.c.1558) server stopped by UID = 0 PID = 1359 
2017-09-09 13:34:19: (log.c.164) server started 
2017-09-09 13:37:14: (mod_fastcgi.c.1754) connect failed: Connection refused on unix:/run/php-fcgi.socket-0 
2017-09-09 13:37:14: (mod_fastcgi.c.3021) backend died; we'll disable it for 1 seconds and send the request to another backend instead: reconnects: 0 load: 1 
2017-09-09 13:37:14: (mod_fastcgi.c.1112) the fastcgi-backend /usr/bin/php-cgi failed to start: 
2017-09-09 13:37:14: (mod_fastcgi.c.1116) child exited with status 5 /usr/bin/php-cgi 
2017-09-09 13:37:14: (mod_fastcgi.c.1119) If you're trying to run your app as a FastCGI backend, make sure you're using the FastCGI-enabled version.
If this is PHP on Gentoo, add 'fastcgi' to the USE flags. 
2017-09-09 13:37:14: (mod_fastcgi.c.2838) ERROR: spawning fcgi failed. 
```

**Comment by daniel-fabteam** [comment]
Hi Frédéric,

The new FABUI is compatible with all units out there.

However there are a lot of decompression errors in the logs you attached.
`SQUASHFS error: lzo decompression failed, data probably corrupt`

Files on the sdcard are corrupted so try to flash the sdcard again or even try a different sdcard.

**Comment by Fensterbank** [comment]
Thanks for the response.
I'll try it again asap and give feedback here.

**Comment by dr4Ke** [comment]
For what it's worth, I had the same issues during the beta phase. I had to give up the original fabtotum sdcard because there was too often corruption on it.

**Comment by Fensterbank** [comment]
So I want to give it another try.
Loaded the latest sd_card.zip (`sha1sum ab6ebd6d437ea4e2ff7c2a39e4c30a0b21342289`), extracted all files (tried two different tools and the `unzip` in linux command line) to a new 16 GB sd card.

But now it just got stuck. I delayed the boot time in the config to make sure it's not hanging at `random: nonblocking pool is initialized` (https://github.com/FABtotum/fabui-colibri/issues/199) and indeed it stops on `First Time Boot` after having the network. I also tried it without network. Doesn't change anything.

The IP configuration is correct and I can even ping this machine. But that's all.
![img_20180320_181739](https://user-images.githubusercontent.com/1684826/37671934-1a40b8b4-2c6d-11e8-897a-0720a4b4aede.jpg)

Also it's not freezed. I can type in things and when disconnecting or connecting network or usb devices there are messages on the screen... But whatever is in your script, it does not run.

I don't know what I can do anymore... I mean, it's the original Fabtotum from Crowdfunding with the original Raspberry Pi. It should work!
I'm about to throw the whole thing in the trash and declare the Fabtotum project dead for me. :(

Seriously, does anyone sell those working sd cards? Can I send my Fabtotum somewhere to fix that? I'm at my wits' end.

**Comment by Fensterbank** [comment]
Indeed, it worked with another SD card.
There was a bit confusion (maybe someone received a mail from github with another content) because nothing happened on screen and while I thought it's stuck again, there was the web interface just waiting for me to start the installation.

Maybe a boot message like "please open 192.168.1.50 to continue the installation" would be helpful. 😉
